# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  namespace: default
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: 
    src: ./
    exclude:
      - '*.!(js|txt|json)'
      - 'backUp/**'
      - 'icon/**'
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs12.16
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 64 # 内存大小，单位MB
  timeout: 3600 # 超时时间，单位秒
  asyncRunEnable: true # 是否启用异步执行
  retryNum: 0
  events: #触发器
    - timer:
        parameters:
          name: config
          cronExpression: "0 0 * * * * *"
          enable: true
          argument: config
    - timer: #京东超市
        parameters:
          name: supermarket
          cronExpression: "59 59 23 * * * *"
          enable: true
          argument: jd_blueCoin
    - timer: #天天加速
        parameters:
          name: joy_speed
          cronExpression: "0 45 14,19 * * * *"
          enable: true
          argument: jd_speed
    - timer: #bean_change
        parameters:
          name: bean_change
          cronExpression: "0 0 18 * * * *"
          enable: true
          argument: jd_bean_change
  environment: #  环境变量
    variables: #  环境变量对象
